### ISSUE TITLE
Provide API endpoint to allow twtxt clients to publish on htwtxt

### ISSUE THREAD

**Issue by buckket** [plomlompom/htwtxt#3]
See this issue: https://github.com/buckket/twtxt/issues/70

Currently you can’t specify your own date, which would result in deviations between the local twtxt file and the one created on htwtxt.

**Comment by plomlompom** [comment]
Providing an API to publish individual twtxt messages sounds reasonable, I'll look into implementing it after the weekend.

Undecided about whether to support providing the whole twtxt line including the date or just the post \t part. Allowing appending of the raw line including the date string opens up ways to disturb the feeds' formatting in ways I had not yet considered an issue for htwtxt. What's currently the problem with deviations between one's local twtxt file and the one created on htwtxt?

**Comment by buckket** [comment]
The timestamps may come in handy when linking to a specific tweet, having the same content with different timestamps would corrupt that idea. (That’s if the user later decides to switch his hosting solution…)

It sure would be easier to just accept the whole line and append it without further processing. Security wise it might be clever to accept the timestamp and the text separately, and do the formatting on the server.

Not that familiar with go though, would provide a PR otherwise.

**Comment by plomlompom** [comment]
Growing what the user is allowed to manipulate in the feed files seems a serious design question to me, to which the conservative answer would be "don't do it, just allow the same kind of input by API that you allow on the HTML interface". I don't want to grow the scope of the project hastily, which is why I'm currently inclined to go with this conservative approach for the endpoint (i.e. only allow input of the post-"\t" pre-"\n" message, with the server determining the timestamp string).

My mind might be changed by concrete benefits that opening up such an API would bring. But I don't see them yet. What is the current state of discussion about how to link individual messages? If the solution is based on a hash that includes the feed's URL, the text file on the server would be the authoritative version, so the file on the local machine would need to be synchronized to it, not vice versa. What /is/ the authority of the text file on the user's local machine in the twtxt ecosystem currently when it's not directly available on the web? Unless these questions are thoroughly answered, I don't see a benefit in growing the server's scope for purposes of synchronization between the two file locations.

**Comment by plomlompom** [comment]
I feel a bit stupid for not seeing this myself right away, but as buckket shows in https://github.com/buckket/twtxt/commit/dbdd54d3839858ce1ad6956e92c54be697084453, the basic API for appending a new twtxt message is already implemented (by way of the ability to just send a POST request to /feeds as the input form on htwtxt's start page does). Added documentation of this to the README.
